FROM python:3.9

ENV CURRENT_ENVIRONMENT production
WORKDIR /app
COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT python3 -m flask run --host=0.0.0.0